language: rust

cache: cargo

sudo: false

rust:
  - stable
  - beta
  - nightly

script:
  - cargo build
  - cargo test

matrix:
  allow_failures:
    - rust: nightly

after_success:
- if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then
  cargo bench;
  fi
